"""Initial migration

Revision ID: 5b924254f5a6
Revises: 
Create Date: 2024-10-27 02:29:40.093159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b924254f5a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('producer', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('key_signature', sa.String(length=10), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('time_signature', sa.String(length=10), nullable=True),
    sa.Column('chord_progression', sa.String(length=200), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
